const en = {
  nav: { home: "Home", gallery: "Gallery", shop: "Shop", cart: "Cart", login: "Login" },
  hero: { title: "Broken Beauty", subtitle: "Unique artworks crafted from shattered spirits bottles, preserved in resin", cta: "Explore Gallery", shop_cta: "Shop Now" },
  gallery: { title: "The Collection", subtitle: "Each piece is a unique composition of broken bottle glass, frozen in time with crystal-clear resin", sold: "Sold", in_cart: "In Cart" },
  shop: { title: "Acquire a Masterpiece", subtitle: "Browse exclusive artworks — each piece is unique and one-of-a-kind", added: "Added to cart!", buy: "Buy Now", sold: "Sold", no_stock: "No artworks available at the moment" },
  cart: { title: "Your Cart", empty: "Your cart is empty", empty_msg: "Browse the gallery to add unique artworks to your collection", total: "Total", checkout: "Proceed to Checkout", remove: "Remove", order_placed: "Order placed successfully!", shipping_title: "Shipping Information", name: "Name", surname: "Surname", name_surname: "Name and Surname", address: "Address and Street Number", city: "City", postal: "Postal Code", country: "Country", shipping_time: "Shipping Method", standard: "Standard (5-7 business days)", express: "Express (2-3 business days)", notes: "Order Notes (optional)", recipient: "Recipient", order_summary: "Order Summary", items: "Items", shipping_cost: "Shipping Cost", estimated_delivery: "Estimated delivery", place_order: "Place Order", success_msg: "Thank you for your order! You will receive a confirmation email shortly.", order_number: "Order Number" },
  user: { title: "My Account", login_title: "Login", register_title: "Register", username: "Username", password: "Password", login_btn: "Login", register_btn: "Create Account", no_account: "Don't have an account?", has_account: "Already have an account?", register_here: "Register here", login_here: "Login here", name: "Name", surname: "Surname", address: "Address", welcome: "Welcome", logout: "Logout", my_orders: "My Orders", no_orders: "No orders yet", order: "Order", date: "Date", status: "Status", items_ordered: "Items", total_paid: "Total", admin_panel: "Admin Panel", wrong: "Invalid username or password", error_register: "Registration failed" },
  admin: { back: "Back to site", logout: "Logout", dashboard: "Admin Dashboard", login_title: "Admin Login", add_title: "Add New Artwork", add_desc: "Add a new artwork to the collection", title_en: "Title (English)", title_it: "Title (Italian)", desc_en: "Description (English)", desc_it: "Description (Italian)", price: "Price (€)", image_path: "Image path", category: "Category", add_btn: "Add Artwork", added_ok: "Artwork added successfully", manage: "Manage Artworks", remove: "Remove", confirm_remove: "Are you sure you want to remove this artwork?", removed_ok: "Artwork removed", username: "Username", password: "Password", login: "Login", wrong: "Invalid credentials" },
  footer: { tagline: "Where broken glass becomes timeless art", rights: "All rights reserved" }
}

const it = {
  nav: { home: "Home", gallery: "Galleria", shop: "Negozio", cart: "Carrello", login: "Accedi" },
  hero: { title: "Bellezza Infranta", subtitle: "Opere d'arte uniche realizzate con bottiglie di liquori in frantumi, preservate nella resina", cta: "Esplora la Galleria", shop_cta: "Acquista Ora" },
  gallery: { title: "La Collezione", subtitle: "Ogni pezzo è una composizione unica di vetro di bottiglia frantumato, congelato nel tempo con resina cristallina", sold: "Venduto", in_cart: "Nel Carrello" },
  shop: { title: "Acquisisci un Capolavoro", subtitle: "Sfoglia opere esclusive — ogni pezzo è unico e irripetibile", added: "Aggiunto al carrello!", buy: "Acquista", sold: "Venduto", no_stock: "Nessuna opera disponibile al momento" },
  cart: { title: "Il Tuo Carrello", empty: "Il carrello è vuoto", empty_msg: "Esplora la galleria per aggiungere opere uniche alla tua collezione", total: "Totale", checkout: "Procedi al Checkout", remove: "Rimuovi", order_placed: "Ordine effettuato con successo!", shipping_title: "Informazioni di Spedizione", name: "Nome", surname: "Cognome", name_surname: "Nome e Cognome", address: "Indirizzo e Numero Civico", city: "Città", postal: "Codice Postale", country: "Paese", shipping_time: "Metodo di Spedizione", standard: "Standard (5-7 giorni lavorativi)", express: "Espresso (2-3 giorni lavorativi)", notes: "Note sull'Ordine (opzionale)", recipient: "Destinatario", order_summary: "Riepilogo Ordine", items: "Articoli", shipping_cost: "Costo Spedizione", estimated_delivery: "Consegna prevista", place_order: "Conferma Ordine", success_msg: "Grazie per l'ordine! Riceverai una email di conferma a breve.", order_number: "Numero Ordine" },
  user: { title: "Il Mio Account", login_title: "Accedi", register_title: "Registrati", username: "Nome utente", password: "Password", login_btn: "Accedi", register_btn: "Crea Account", no_account: "Non hai un account?", has_account: "Hai già un account?", register_here: "Registrati qui", login_here: "Accedi qui", name: "Nome", surname: "Cognome", address: "Indirizzo", welcome: "Benvenuto", logout: "Esci", my_orders: "I Miei Ordini", no_orders: "Nessun ordine ancora", order: "Ordine", date: "Data", status: "Stato", items_ordered: "Articoli", total_paid: "Totale", admin_panel: "Pannello Admin", wrong: "Nome utente o password errati", error_register: "Registrazione fallita" },
  admin: { back: "Torna al sito", logout: "Esci", dashboard: "Pannello Admin", login_title: "Accesso Admin", add_title: "Aggiungi Nuova Opera", add_desc: "Aggiungi una nuova opera alla collezione", title_en: "Titolo (Inglese)", title_it: "Titolo (Italiano)", desc_en: "Descrizione (Inglese)", desc_it: "Descrizione (Italiano)", price: "Prezzo (€)", image_path: "Percorso immagine", category: "Categoria", add_btn: "Aggiungi Opera", added_ok: "Opera aggiunta con successo", manage: "Gestisci Opere", remove: "Rimuovi", confirm_remove: "Sei sicuro di voler rimuovere quest'opera?", removed_ok: "Opera rimossa", username: "Nome utente", password: "Password", login: "Accedi", wrong: "Credenziali non valide" },
  footer: { tagline: "Dove il vetro rotto diventa arte senza tempo", rights: "Tutti i diritti riservati" }
}

export default { en, it }